---
services:
  named:
    #build:
    #  context: .
    image: ghcr.io/gottaeat/docker-bind:latest
    container_name: named
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
